# permissions for end users to view modelserves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: modelserve-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: modelserve-viewer-role
rules:
- apiGroups:
  - model.example.com
  resources:
  - modelserves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - model.example.com
  resources:
  - modelserves/status
  verbs:
  - get
